# Generated by Django 4.0.3 on 2022-04-14 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacion', '0001_Creacion_tabla_Usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ROL',
            new_name='rol',
        ),
    ]
