# Generated by Django 4.0.3 on 2022-04-07 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_Agregue_Columna_Descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
