# Generated by Django 4.0.3 on 2022-04-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_Creacion_Tabla_Platos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platos',
            new_name='Plato',
        ),
    ]
