# Generated by Django 4.0.3 on 2022-04-18 02:24

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_change_Plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='foto',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
